# This rule is not used by the project namespace-cost-governor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cost.cost.platform.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-cost-governor
    app.kubernetes.io/managed-by: kustomize
  name: namespacebudget-viewer-role
rules:
- apiGroups:
  - cost.cost.platform.io
  resources:
  - namespacebudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cost.cost.platform.io
  resources:
  - namespacebudgets/status
  verbs:
  - get
