---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cost.cost.platform.io
  resources:
  - costreports
  - namespacebudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cost.cost.platform.io
  resources:
  - costreports/finalizers
  - namespacebudgets/finalizers
  verbs:
  - update
- apiGroups:
  - cost.cost.platform.io
  resources:
  - costreports/status
  - namespacebudgets/status
  verbs:
  - get
  - patch
  - update
