apiVersion: cost.cost.platform.io/v1alpha1
kind: CostReport
metadata:
  labels:
    app.kubernetes.io/name: namespace-cost-governor
    app.kubernetes.io/managed-by: kustomize
  name: costreport-sample
spec:
  # TODO(user): Add fields here
