//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccumulatedUsage) DeepCopyInto(out *AccumulatedUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccumulatedUsage.
func (in *AccumulatedUsage) DeepCopy() *AccumulatedUsage {
	if in == nil {
		return nil
	}
	out := new(AccumulatedUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Actions) DeepCopyInto(out *Actions) {
	*out = *in
	if in.OnWarning != nil {
		in, out := &in.OnWarning, &out.OnWarning
		*out = make([]Action, len(*in))
		copy(*out, *in)
	}
	if in.OnExceeded != nil {
		in, out := &in.OnExceeded, &out.OnExceeded
		*out = make([]Action, len(*in))
		copy(*out, *in)
	}
	if in.OnHardLimit != nil {
		in, out := &in.OnHardLimit, &out.OnHardLimit
		*out = make([]Action, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Actions.
func (in *Actions) DeepCopy() *Actions {
	if in == nil {
		return nil
	}
	out := new(Actions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReport) DeepCopyInto(out *CostReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReport.
func (in *CostReport) DeepCopy() *CostReport {
	if in == nil {
		return nil
	}
	out := new(CostReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportList) DeepCopyInto(out *CostReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportList.
func (in *CostReportList) DeepCopy() *CostReportList {
	if in == nil {
		return nil
	}
	out := new(CostReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportSpec) DeepCopyInto(out *CostReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportSpec.
func (in *CostReportSpec) DeepCopy() *CostReportSpec {
	if in == nil {
		return nil
	}
	out := new(CostReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportStatus) DeepCopyInto(out *CostReportStatus) {
	*out = *in
	out.TotalCost = in.TotalCost
	if in.TopConsumers != nil {
		in, out := &in.TopConsumers, &out.TopConsumers
		*out = make([]TopConsumer, len(*in))
		copy(*out, *in)
	}
	if in.IdleEvents != nil {
		in, out := &in.IdleEvents, &out.IdleEvents
		*out = make([]IdleEvent, len(*in))
		copy(*out, *in)
	}
	if in.SuspendedEvents != nil {
		in, out := &in.SuspendedEvents, &out.SuspendedEvents
		*out = make([]SuspensionEvent, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportStatus.
func (in *CostReportStatus) DeepCopy() *CostReportStatus {
	if in == nil {
		return nil
	}
	out := new(CostReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exclusion) DeepCopyInto(out *Exclusion) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exclusion.
func (in *Exclusion) DeepCopy() *Exclusion {
	if in == nil {
		return nil
	}
	out := new(Exclusion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleEvent) DeepCopyInto(out *IdleEvent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleEvent.
func (in *IdleEvent) DeepCopy() *IdleEvent {
	if in == nil {
		return nil
	}
	out := new(IdleEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleThreshold) DeepCopyInto(out *IdleThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleThreshold.
func (in *IdleThreshold) DeepCopy() *IdleThreshold {
	if in == nil {
		return nil
	}
	out := new(IdleThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdleWorkload) DeepCopyInto(out *IdleWorkload) {
	*out = *in
	in.IdleSince.DeepCopyInto(&out.IdleSince)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdleWorkload.
func (in *IdleWorkload) DeepCopy() *IdleWorkload {
	if in == nil {
		return nil
	}
	out := new(IdleWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBudget) DeepCopyInto(out *NamespaceBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBudget.
func (in *NamespaceBudget) DeepCopy() *NamespaceBudget {
	if in == nil {
		return nil
	}
	out := new(NamespaceBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBudgetList) DeepCopyInto(out *NamespaceBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBudgetList.
func (in *NamespaceBudgetList) DeepCopy() *NamespaceBudgetList {
	if in == nil {
		return nil
	}
	out := new(NamespaceBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBudgetSpec) DeepCopyInto(out *NamespaceBudgetSpec) {
	*out = *in
	out.Monthly = in.Monthly
	out.IdleThreshold = in.IdleThreshold
	in.Actions.DeepCopyInto(&out.Actions)
	if in.Exclusions != nil {
		in, out := &in.Exclusions, &out.Exclusions
		*out = make([]Exclusion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBudgetSpec.
func (in *NamespaceBudgetSpec) DeepCopy() *NamespaceBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBudgetStatus) DeepCopyInto(out *NamespaceBudgetStatus) {
	*out = *in
	out.CurrentUsage = in.CurrentUsage
	out.Accumulated = in.Accumulated
	in.LastReconcile.DeepCopyInto(&out.LastReconcile)
	if in.IdleWorkloads != nil {
		in, out := &in.IdleWorkloads, &out.IdleWorkloads
		*out = make([]IdleWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBudgetStatus.
func (in *NamespaceBudgetStatus) DeepCopy() *NamespaceBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspensionEvent) DeepCopyInto(out *SuspensionEvent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspensionEvent.
func (in *SuspensionEvent) DeepCopy() *SuspensionEvent {
	if in == nil {
		return nil
	}
	out := new(SuspensionEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopConsumer) DeepCopyInto(out *TopConsumer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopConsumer.
func (in *TopConsumer) DeepCopy() *TopConsumer {
	if in == nil {
		return nil
	}
	out := new(TopConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TotalCost) DeepCopyInto(out *TotalCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TotalCost.
func (in *TotalCost) DeepCopy() *TotalCost {
	if in == nil {
		return nil
	}
	out := new(TotalCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Usage) DeepCopyInto(out *Usage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Usage.
func (in *Usage) DeepCopy() *Usage {
	if in == nil {
		return nil
	}
	out := new(Usage)
	in.DeepCopyInto(out)
	return out
}
